# action.yml
name: 'Set CodeQL Languages'
description: 'Auto-populate the Actions matrix definition to include languages for CodeQL'
icon: lock
inputs:
  access-token:  
    description: 'github token'
    required: true
  repository:
    description: 'Repository information. owner/repo-name'
    required: true
  changed_files_detection:
    description: 'Repository information. owner/repo-name'
    default: "false"
    required: true
  pull_number:
    description: 'PR Number'
    required: false
  exclude:
    description: 'Use a comma separated list here to exclude specific languges from your CodeQL scan.  Example: "python, java"'
    required: false
outputs:
  languages:
    description: 'List of languages that will set the job matrix'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{ inputs.access-token }}
   - ${{ inputs.repository }}
   - ${{ inputs.changed_files_detection }}
   - ${{ inputs.pull_number }}
   - ${{ inputs.exclude }}

